name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest
    container: ghcr.io/hyperk/hk-software:main
    steps:
    - name: Make setup script
      run: |
        cd /usr/local/hk/
        echo source /usr/local/hk/hk-pilot/setup.sh >> setup.sh
        echo source /usr/local/hk/hk-software/install-Linux_x86_64-gcc_8-python_3.8.13/setup.sh >> setup.sh
    - name: Framework build
      run: |
        cd /usr/local/hk/ToolFrameworkCore/src/
        sed -i 's!gray!grey!' src/Logging/Logging.h
        make
    - uses: actions/checkout@v2
    - name: get submodules
      run: |
        git submodule init
        git submodule update
    - name: link
      run: |
        mkdir -p /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/
        ln -s $PWD/ /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/
    - name: build WCSim
      run: |
        sed -i -e 's!geant4!./geant4!' /usr/local/hk/hk-software/install-Linux_x86_64-gcc_8-python_3.8.13/setup.sh
        source /usr/local/hk/setup.sh
        cd /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        mkdir OriginalWCSim_build
        cd OriginalWCSim_build
        cmake ../OriginalWCSim
        make
        make install
        echo source $PWD/this_wcsim.sh >> /usr/local/hk/setup.sh
    - name: build hk-datamodel
      run: |
        source /usr/local/hk/setup.sh
        git clone https://github.com/tdealtry/hk-DataModel.git /usr/local/hk/hk-ToolApp/hk-DataModel
        cd /usr/local/hk/hk-ToolApp/hk-DataModel
        make
    - name: build
      run: |
        source /usr/local/hk/setup.sh
        cd /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        make
