name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest
    container: ghcr.io/hyperk/hk-software:main
    steps:
    - name: Make setup script
      run: |
        cd /usr/local/hk/
        source /usr/local/hk/hk-pilot/setup.sh >> setup.sh
        source /usr/local/hk/hk-software/install-Linux_x86_64-gcc_8-python_3.8.13/setup.sh >> setup.sh
        source /usr/local/hk/ROOT/install-Linux_x86_64-gcc_8-python_3.8.13/bin/thisroot.sh >> setup.sh
        source /usr/local/hk/Geant4/install-Linux_x86_64-gcc_8-python_3.8.13/bin/geant4.sh >> setup.sh
    - name: Framework build
      run: |
        cd /usr/local/hk/ToolFrameworkCore/src/
        sed -i 's!gray!grey!' src/Logging/Logging.h
        make
    - name: build hk-datamodel
      run: |
        ls /usr/local/hk/
        cat /usr/local/hk/setup.sh
        source /usr/local/hk/setup.sh
        git clone https://github.com/tdealtry/hk-DataModel.git /usr/local/hk/hk-ToolApp/hk-DataModel
        cd /usr/local/hk/hk-ToolApp/hk-DataModel
        make
    - uses: actions/checkout@v2
    - name: build WCSim
      run: |
        source /usr/local/hk/setup.sh
        mkdir OriginalWCSim_build
        cd OriginalWCSim_build
        cmake ../OriginalWCSim
        make
        make install
    - name: build
      run: |
        source /usr/local/hk/setup.sh
        pwd
        ls
        mkdir -p /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        ln -s $PWD/OriginalWCSim_build/ /usr/local/hk/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        export WCSIMDIR=$PWD/OriginalWCSim/
        make
